<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1873</NoWarn>
    <UserSecretsId>06cbc069-cc6f-40af-b2c5-410ba1a28877</UserSecretsId>
</PropertyGroup>

</Project>
